### ISSUE TITLE
Dollar TODO list

### ISSUE THREAD

**Issue by kiri1701** [kiri1701/TDD_python#5]
- [x] $5 + 10CHF = $10 if rate is 2:1
- [x] hashCode()
- [x] Equivalence comparison with Null
- [x] Equivalence comparison with other objects
- [x]  Overlap in Dollar and Franc
- [x] generalize equals
- [x] generalize times
- [ ] compare Franc and Dollar
